"""Export/check the selected authored Sunbloom views. --write opts into exports."""
import argparse
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / 'assets/environment/ellionar-sunbloom-crowns-v2'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def frames(source):
    # The generated sheet has unequal view cells. Isolate those cells, then
    # translate into equal canvases; never independently enlarge a side view.
    result = []
    for label, (x0, x1) in zip(['front', 'right', 'rear', 'left'], [(0, 675), (675, 1090), (1090, 1750), (1750, 2170)]):
        region = source.crop((x0, 0, x1, 725))
        bounds = region.getchannel('A').point(lambda v: 255 if v >= 8 else 0).getbbox()
        assert bounds[2]-bounds[0] <= 700 and bounds[3]-bounds[1] <= 671, 'Common canvas would clip specimen'
        anchor_x = round((bounds[0] + bounds[2]) / 2)
        bottom = bounds[3]
        rect = [x0, bottom - 671, x1, bottom]
        offset = [350 - anchor_x, 0]
        canvas = Image.new('RGBA', (700, 671))
        canvas.alpha_composite(source.crop(rect), offset)
        image = canvas.resize((512, 491), Image.Resampling.LANCZOS)
        result.append((image, {'id': label, 'requestedTurnDegrees': len(result) * 90,
            'sourceRectPx': rect, 'translationPx': offset,
            'contactProxyPx': [x0 + anchor_x, bottom],
            'contactMethod': 'alpha>=8 lower bound and horizontal silhouette center; anatomical root not certified',
            'rectPx': [64 + len(result) * 640, 64, 512, 491]}))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    source_path = PACK / 'source.png'
    source = Image.open(source_path).convert('RGBA')
    assert source.size == (2170, 725), 'Selected source canvas changed'
    reference = ROOT / 'assets/environment/ellionar-sunbloom-views-v1/source.png'
    generated = frames(source)
    manifest_path = PACK / 'manifest.json'
    if manifest_path.exists():
        selected = json.loads(manifest_path.read_text())
        assert selected['sourceSha256'] == digest(source_path), 'Selected source changed; review a new version explicitly'
        assert selected['referenceSha256'] == digest(reference), 'Selected reference changed'
    if args.write:
        page = Image.new('RGBA', (2560, 619))
        preview = Image.new('RGBA', (2048, 531), '#727a57')
        for index, (frame, row) in enumerate(generated):
            page.alpha_composite(frame, tuple(row['rectPx'][:2]))
            preview.alpha_composite(frame, (index * 512, 20))
        page.save(PACK / 'sunbloom-crowns-atlas.webp', quality=86, method=6, exact=True)
        preview.convert('RGB').save(PACK / 'preview.png')
        manifest = {'schemaVersion': 1, 'maturity': 'authored-runtime-candidate',
            'sourceFile': 'source.png', 'sourceSha256': digest(source_path), 'sourceDimensionsPx': list(source.size),
            'sourceOutput': 'exec-689ffdff-b792-4cb6-88fc-53b042d93900.png',
            'reference': '../ellionar-sunbloom-views-v1/source.png', 'referenceSha256': digest(reference),
            'prompts': 'PROMPTS.json', 'atlasFile': 'sunbloom-crowns-atlas.webp', 'atlasSha256': digest(PACK / 'sunbloom-crowns-atlas.webp'),
            'atlasSizePx': [2560, 619], 'frameSizePx': [512, 491], 'gutterPx': 64,
            'worldSize': [0.88654, 0.85], 'pivot': [0.5, 1], 'frames': [row for _, row in generated],
            'sourceCanvasPerFramePx': [700, 671], 'perViewScale': False, 'mirroredViews': False,
            'measured3DCapture': False, 'anatomicalRootAlignmentCertified': False}
        (PACK / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
        config = {key: manifest[key] for key in ['atlasSizePx', 'frameSizePx', 'worldSize', 'pivot']}
        config['url'] = './assets/environment/ellionar-sunbloom-crowns-v2/sunbloom-crowns-atlas.webp'
        config['rectsPx'] = [row['rectPx'] for _, row in generated]
        (ROOT / 'src/sunbloom-crown-pack.mjs').write_text('// Generated by scripts/build-sunbloom-crowns.py --write.\nexport const SUNBLOOM_CROWN_PACK = Object.freeze(' + json.dumps(config) + ');\n')
    manifest = json.loads((PACK / 'manifest.json').read_text())
    assert manifest['atlasFile'] == 'sunbloom-crowns-atlas.webp' and manifest['sourceFile'] == 'source.png', 'File binding changed'
    assert manifest['frameSizePx'] == [512,491] and manifest['gutterPx'] == 64, 'Frame contract changed'
    assert manifest['worldSize'] == [.88654,.85] and manifest['pivot'] == [.5,1], 'Scale/pivot contract changed'
    assert manifest['sourceSha256'] == digest(source_path) and manifest['referenceSha256'] == digest(reference), 'Source/reference changed'
    assert manifest['atlasSha256'] == digest(PACK / manifest['atlasFile']), 'Atlas changed'
    assert manifest['frames'] == [row for _, row in generated], 'View extraction changed'
    atlas = Image.open(PACK / manifest['atlasFile']).convert('RGBA')
    assert list(atlas.size) == manifest['atlasSizePx'], 'Atlas dimensions changed'
    for expected, row in generated:
        x, y, w, h = row['rectPx']
        actual = atlas.crop((x, y, x+w, y+h))
        assert actual.getchannel('A').tobytes() == expected.getchannel('A').tobytes(), row['id'] + ': alpha changed'
    config_text = (ROOT / 'src/sunbloom-crown-pack.mjs').read_text()
    config = json.loads(config_text.split('Object.freeze(', 1)[1].rsplit(');', 1)[0])
    assert config['rectsPx'] == [row['rectPx'] for _, row in generated] and config['atlasSizePx'] == list(atlas.size), 'Runtime rectangles differ'
    assert config['frameSizePx'] == manifest['frameSizePx'] and config['url'] == './assets/environment/ellionar-sunbloom-crowns-v2/sunbloom-crowns-atlas.webp', 'Runtime file/frame binding differs'
    assert config['worldSize'] == manifest['worldSize'] and config['pivot'] == manifest['pivot'], 'Runtime registration differs'
    print(json.dumps({'views': 4, 'decodedAlphaExact': True, 'commonScale': True, 'mirroredViews': False,
        'anatomicalRootAlignmentCertified': False, 'measured3DCapture': False}))


if __name__ == '__main__':
    main()
