"""Export/check full/worked Veilcap views with paired source-coordinate registration."""
import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from PIL import Image

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / 'assets/environment/vesperra-veilcap-worked-v2'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    registration = json.loads((PACK/'registration.json').read_text())
    reference = PACK/registration['reference']
    assert sha(PACK/'source.png') == registration['sourceSha256']
    assert sha(reference) == registration['referenceSha256']
    full = Image.open(reference).convert('RGBA')
    worked = Image.open(PACK/'source.png').convert('RGBA')
    assert full.size == (2172,724) and worked.size == (2172,724)
    spec = importlib.util.spec_from_file_location('crowns',ROOT/'scripts/build-veilcap-views.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    original = module.frames(full)
    generated = []
    for state,source in [('full',full),('worked',worked)]:
        for i,(_,row) in enumerate(original):
            x0,x1 = [(0,590),(590,1090),(1090,1660),(1660,2172)][i]
            fb = full.crop((x0,0,x1,724)).getchannel('A').point(lambda a:255 if a>=8 else 0).getbbox()
            wb = worked.crop((x0,0,min(x1,2172),724)).getchannel('A').point(lambda a:255 if a>=8 else 0).getbbox()
            bottom = max(fb[3],wb[3])
            center = row['contactProxyPx'][0]-x0
            rect = [x0,bottom-591,min(x1,source.width),bottom]
            offset = [282-center,0]
            bounds = fb if state=='full' else wb
            assert bounds[0]+offset[0]>=0 and bounds[2]+offset[0]<=564
            assert bottom-bounds[1]<=591
            canvas = Image.new('RGBA',(564,591))
            canvas.alpha_composite(source.crop(rect),tuple(offset))
            frame = canvas.resize((512,537),Image.Resampling.LANCZOS)
            generated.append((frame,{'id':row['id'],'state':state,
                'rectPx':[64+i*640,64+(0 if state=='full' else 665),512,537],
                'sourceRectPx':rect,'translationPx':offset,
                'pairedContactProxyPx':[x0+center,bottom],
                'contactMethod':'reference silhouette center and common lower bound; source-coordinate pairing, anatomical crown not certified'}))
    rows = [r for _,r in generated]
    config = {'url':'./assets/environment/vesperra-veilcap-worked-v2/veilcap-worked-atlas.webp',
        'atlasSizePx':[2560,1330],'frameSizePx':[512,537],'worldSize':[.61614,.65],'pivot':[.5,1],
        'rectsPx':[r['rectPx'] for r in rows[:4]],'workedRectsPx':[r['rectPx'] for r in rows[4:]]}
    config_text = '// Generated by scripts/build-veilcap-worked.py --write.\nexport const VEILCAP_WORKED_PACK = Object.freeze('+json.dumps(config)+');\n'
    if args.write:
        atlas = Image.new('RGBA',(2560,1330))
        for frame,row in generated:
            atlas.alpha_composite(frame,tuple(row['rectPx'][:2]))
        atlas.save(PACK/'veilcap-worked-atlas.webp',quality=86,method=6,exact=True)
        manifest = {'sourceSha256':sha(PACK/'source.png'),'referenceSha256':sha(reference),
            'atlasFile':'veilcap-worked-atlas.webp','atlasSha256':sha(PACK/'veilcap-worked-atlas.webp'),
            'atlasSizePx':[2560,1330],'frameSizePx':[512,537],'sourceCanvasPerFramePx':[564,591],
            'gutterPx':64,'worldSize':[.61614,.65],'pivot':[.5,1],'frames':rows,'perViewScale':False,
            'anatomicalRootAlignmentCertified':False,'runtimeIntegrated':True}
        (PACK/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        (ROOT/'src/veilcap-worked-pack.mjs').write_text(config_text)
    manifest = json.loads((PACK/'manifest.json').read_text())
    assert manifest['sourceSha256'] == sha(PACK/'source.png') and manifest['referenceSha256'] == sha(reference)
    assert manifest['atlasSha256'] == sha(PACK/'veilcap-worked-atlas.webp') and manifest['frames'] == rows
    assert manifest['worldSize'] == config['worldSize'] and manifest['pivot'] == [.5,1]
    assert manifest['perViewScale'] is False and manifest['gutterPx'] == 64
    assert manifest['frameSizePx'] == [512,537] and manifest['sourceCanvasPerFramePx'] == [564,591]
    assert (ROOT/'src/veilcap-worked-pack.mjs').read_text() == config_text
    atlas = Image.open(PACK/'veilcap-worked-atlas.webp').convert('RGBA')
    assert list(atlas.size) == manifest['atlasSizePx'] == [2560,1330]
    for frame,row in generated:
        x,y,w,h = row['rectPx']
        assert atlas.crop((x,y,x+w,y+h)).getchannel('A').tobytes() == frame.getchannel('A').tobytes()
    print(json.dumps({'frames':8,'decodedAlphaExact':True,'pairedSourceCoordinates':True,'perViewScale':False,'anatomicalRootAlignmentCertified':False}))


if __name__ == '__main__':
    main()
