"""Export/check twelve shared-scale pod-vine full/worked/low frames."""
import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from PIL import Image

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / 'assets/environment/vesperra-podvine-low-v1'


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    registration = json.loads((PACK / 'registration.json').read_text())
    assert sha(PACK / 'source.png') == registration['sourceSha256']
    assert sha(PACK / registration['reference']) == registration['referenceSha256']
    source = Image.open(PACK / 'source.png').convert('RGBA')
    assert source.size == (2169, 725)
    spec = importlib.util.spec_from_file_location('worked', ROOT / 'scripts/build-podvine-worked-review.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    generated = module.generate_frames()
    for i, (x0, x1) in enumerate([(0,725), (725,1040), (1040,1780), (1780,2169)]):
        b = source.crop((x0,0,x1,725)).getchannel('A').point(lambda v:255 if v>=8 else 0).getbbox()
        assert [x0+b[0],b[1],x0+b[2],b[3]] == registration['alphaBoundsByView'][i]
        assert b[3]-b[1] <= 448
        center = round((b[0]+b[2])/2)
        rect = [x0,b[3]-448,x1,b[3]]
        offset = [442-center,0]
        canvas = Image.new('RGBA',(884,448))
        canvas.alpha_composite(source.crop(rect),tuple(offset))
        generated.append((canvas.resize((512,259),Image.Resampling.LANCZOS),{
            'view': generated[i][1]['view'], 'state':'low',
            'rectPx':[64+i*640,838,512,259], 'sourceRectPx':rect,
            'translationPx':offset,'contactProxyPx':[x0+center,b[3]]}))
    rows = [r for _,r in generated]
    config = {'url':'./assets/environment/vesperra-podvine-low-v1/lifecycle-atlas.webp',
        'atlasSizePx':[2560,1161], 'frameSizePx':[512,259], 'worldSize':[1.10431,.55],
        'pivot':[.5,1], 'rectsPx':[r['rectPx'] for r in rows[:4]],
        'workedRectsPx':[r['rectPx'] for r in rows[4:8]], 'lowRectsPx':[r['rectPx'] for r in rows[8:]]}
    config_text = '// Generated by scripts/build-podvine-low-pack.py --write.\nexport const PODVINE_LOW_PACK = Object.freeze('+json.dumps(config)+');\n'
    if args.write:
        atlas = Image.new('RGBA',(2560,1161))
        for frame,row in generated:
            atlas.alpha_composite(frame,tuple(row['rectPx'][:2]))
        atlas.save(PACK / 'lifecycle-atlas.webp',quality=86,method=6,exact=True)
        manifest = {'sourceSha256':sha(PACK/'source.png'),
            'referenceSha256':sha(PACK/registration['reference']),
            'atlasFile':'lifecycle-atlas.webp','atlasSha256':sha(PACK/'lifecycle-atlas.webp'),
            'atlasSizePx':[2560,1161], 'frameSizePx':[512,259], 'gutterPx':64,
            'sourceCanvasPerFramePx':[884,448], 'worldSize':[1.10431,.55], 'pivot':[.5,1],
            'frames':rows,'perViewScale':False,'runtimeIntegrated':True,
            'anatomicalRootAlignmentCertified':False,
            'contactMethod':'silhouette center/lower bound; provisional',
            'fullWorkedSources':'../vesperra-podvine-worked-v1/review-manifest.json'}
        (PACK/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        (ROOT/'src/presentation/assets/plant-packs/podvine-low-pack.mjs').write_text(config_text)
    manifest = json.loads((PACK/'manifest.json').read_text())
    assert manifest['sourceSha256'] == sha(PACK/'source.png')
    assert manifest['referenceSha256'] == sha(PACK/registration['reference'])
    assert manifest['atlasSha256'] == sha(PACK/'lifecycle-atlas.webp')
    assert manifest['frames'] == rows and manifest['worldSize'] == config['worldSize']
    assert manifest['atlasFile'] == 'lifecycle-atlas.webp' and manifest['frameSizePx'] == [512,259]
    assert manifest['gutterPx'] == 64 and manifest['sourceCanvasPerFramePx'] == [884,448]
    assert manifest['pivot'] == [.5,1] and manifest['perViewScale'] is False
    assert (ROOT/'src/presentation/assets/plant-packs/podvine-low-pack.mjs').read_text() == config_text
    atlas = Image.open(PACK/'lifecycle-atlas.webp').convert('RGBA')
    assert list(atlas.size) == manifest['atlasSizePx'] == [2560,1161]
    for frame,row in generated:
        x,y,w,h = row['rectPx']
        assert atlas.crop((x,y,x+w,y+h)).getchannel('A').tobytes() == frame.getchannel('A').tobytes()
    print(json.dumps({'frames':12,'decodedAlphaExact':True,'perViewScale':False,'anatomicalRootAlignmentCertified':False}))


if __name__ == '__main__':
    main()
