"""Export/check full/worked/low Sunbloom views with paired source-coordinate registration."""
import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from PIL import Image

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / 'assets/environment/ellionar-sunbloom-low-v4'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    registration = json.loads((PACK/'registration.json').read_text())
    worked_reference = PACK/registration['reference']
    reference = ROOT/'assets/environment/ellionar-sunbloom-crowns-v2/source.png'
    assert sha(PACK/'source.png') == registration['sourceSha256']
    assert sha(worked_reference) == registration['referenceSha256']
    full = Image.open(reference).convert('RGBA')
    worked = Image.open(worked_reference).convert('RGBA')
    low = Image.open(PACK/'source.png').convert('RGBA')
    assert full.size == (2170,725) and worked.size == low.size == (2169,725)
    spec = importlib.util.spec_from_file_location('crowns',ROOT/'scripts/build-sunbloom-crowns.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    original = module.frames(full)
    generated = []
    for state,source in [('full',full),('worked',worked),('low',low)]:
        for i,(_,row) in enumerate(original):
            x0,_,x1,_ = row['sourceRectPx']
            fb = full.crop((x0,0,x1,725)).getchannel('A').point(lambda a:255 if a>=8 else 0).getbbox()
            wb = worked.crop((x0,0,min(x1,2169),725)).getchannel('A').point(lambda a:255 if a>=8 else 0).getbbox()
            lb = low.crop((x0,0,min(x1,2169),725)).getchannel('A').point(lambda a:255 if a>=8 else 0).getbbox()
            bottom = max(fb[3],wb[3],lb[3])
            center = row['contactProxyPx'][0]-x0
            rect = [x0,bottom-671,min(x1,source.width),bottom]
            offset = [350-center,0]
            bounds = fb if state=='full' else wb if state=='worked' else lb
            assert bounds[0]+offset[0]>=0 and bounds[2]+offset[0]<=700
            assert bottom-bounds[1]<=671
            canvas = Image.new('RGBA',(700,671))
            canvas.alpha_composite(source.crop(rect),tuple(offset))
            frame = canvas.resize((512,491),Image.Resampling.LANCZOS)
            generated.append((frame,{'id':row['id'],'state':state,
                'rectPx':[64+i*640,64+{'full':0,'worked':619,'low':1238}[state],512,491],
                'sourceRectPx':rect,'translationPx':offset,
                'pairedContactProxyPx':[x0+center,bottom],
                'contactMethod':'reference silhouette center and common lower bound; source-coordinate pairing, anatomical crown not certified'}))
    rows = [r for _,r in generated]
    config = {'url':'./assets/environment/ellionar-sunbloom-low-v4/sunbloom-low-atlas.webp',
        'atlasSizePx':[2560,1857],'frameSizePx':[512,491],'worldSize':[.88654,.85],'pivot':[.5,1],
        'rectsPx':[r['rectPx'] for r in rows[:4]],'workedRectsPx':[r['rectPx'] for r in rows[4:8]],'lowRectsPx':[r['rectPx'] for r in rows[8:]]}
    config_text = '// Generated by scripts/build-sunbloom-low.py --write.\nexport const SUNBLOOM_LOW_PACK = Object.freeze('+json.dumps(config)+');\n'
    if args.write:
        atlas = Image.new('RGBA',(2560,1857))
        for frame,row in generated:
            atlas.alpha_composite(frame,tuple(row['rectPx'][:2]))
        atlas.save(PACK/'sunbloom-low-atlas.webp',quality=86,method=6,exact=True)
        manifest = {'sourceSha256':sha(PACK/'source.png'),'referenceSha256':sha(reference),
            'fullReference':'../ellionar-sunbloom-crowns-v2/source.png',
            'workedReference':registration['reference'],'workedReferenceSha256':sha(worked_reference),
            'atlasFile':'sunbloom-low-atlas.webp','atlasSha256':sha(PACK/'sunbloom-low-atlas.webp'),
            'atlasSizePx':[2560,1857],'frameSizePx':[512,491],'sourceCanvasPerFramePx':[700,671],
            'gutterPx':64,'worldSize':[.88654,.85],'pivot':[.5,1],'frames':rows,'perViewScale':False,
            'anatomicalRootAlignmentCertified':False,'runtimeIntegrated':True}
        (PACK/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        (ROOT/'src/sunbloom-low-pack.mjs').write_text(config_text)
    manifest = json.loads((PACK/'manifest.json').read_text())
    assert manifest['sourceSha256'] == sha(PACK/'source.png') and manifest['referenceSha256'] == sha(reference)
    assert manifest['workedReferenceSha256'] == sha(worked_reference)
    assert manifest['atlasSha256'] == sha(PACK/'sunbloom-low-atlas.webp') and manifest['frames'] == rows
    assert manifest['worldSize'] == config['worldSize'] and manifest['pivot'] == [.5,1]
    assert manifest['perViewScale'] is False and manifest['gutterPx'] == 64
    assert manifest['frameSizePx'] == [512,491] and manifest['sourceCanvasPerFramePx'] == [700,671]
    assert (ROOT/'src/sunbloom-low-pack.mjs').read_text() == config_text
    atlas = Image.open(PACK/'sunbloom-low-atlas.webp').convert('RGBA')
    assert list(atlas.size) == manifest['atlasSizePx'] == [2560,1857]
    for frame,row in generated:
        x,y,w,h = row['rectPx']
        assert atlas.crop((x,y,x+w,y+h)).getchannel('A').tobytes() == frame.getchannel('A').tobytes()
    print(json.dumps({'frames':12,'decodedAlphaExact':True,'pairedSourceCoordinates':True,'perViewScale':False,'anatomicalRootAlignmentCertified':False}))


if __name__ == '__main__':
    main()
