import test from 'node:test';
import assert from 'node:assert/strict';
import { createFiniteRoomProbe } from './crowd-finite-retreat-probe.mjs';
const width=12,height=12,step=2.6/30;
const cell=(x,z)=>Math.floor(z+height/2)*width+Math.floor(x+width/2);
const point=c=>({x:c%width-width/2+.5,z:Math.floor(c/width)-height/2+.5});
function setup(){const unit={id:0,team:0,generation:7,orderRevision:3,kind:'infantry',hp:100,x:-1.5,z:.5,path:[cell(.5,.5)],pathIndex:0,moveGoalCell:cell(.5,.5),queuedWaypoints:[],gatherNodeId:null,buildingTargetId:null};const normal={x:1,z:0,target:point(unit.path[0]),stepDistance:step};return {unit,tick:9,remainingStep:step,navigationRevision:2,epoch:4,normal,hasGrant:false,units:[unit],query:{visits:0,neighbors:[],overflow:false},map:{width,height,point,cell,levels:new Int8Array(width*height),isWalkable:()=>true}};}
const probe=()=>createFiniteRoomProbe({ownerId:0,peerIds:[],angle:180,mode:'retreat',startTick:9});
test('external cancellation before activation permanently suppresses the attempt',()=>{const ctx=setup(),p=probe();p.cancel(8,'frontier-route-change');assert.equal(p.select(ctx),ctx.normal);ctx.tick++;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.length,1);assert.equal(p.report.events[0].reason,'frontier-route-change');assert.equal(p.report.events[0].distance,0);});
test('finite diagnostic spends only own available steps, caps displacement and resumes normal steering',()=>{const ctx=setup(),p=probe();let distance=0;for(let i=0;i<9;i++){ctx.tick=9+i;const move=p.select(ctx);assert.ok(move.stepDistance<=ctx.remainingStep);distance+=move.stepDistance;ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;}assert.ok(Math.abs(distance-.75)<1e-9);assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,9);ctx.tick++;assert.equal(p.select(ctx),ctx.normal);assert.equal(ctx.unit.orderRevision,3);assert.deepEqual(ctx.unit.queuedWaypoints,[]);});
test('changed order and expired phase cancel without another intervention step',()=>{for(const change of['order','time']){const ctx=setup(),p=probe();const move=p.select(ctx);ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;if(change==='order')ctx.unit.orderRevision++;else ctx.tick+=12;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,1);assert.equal(p.report.events.at(-1).type,'abort');}});
test('fresh body contact aborts an initially clear corridor',()=>{const ctx=setup(),p=probe();const move=p.select(ctx);ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;ctx.tick++;ctx.query={visits:1,overflow:false,neighbors:[{...ctx.unit,id:1,x:ctx.unit.x-.45,z:.5}]};assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.at(-1).reason,'step-body');assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,1);});
test('Stop eligibility and existing grants prevent speculative intervention',()=>{for(const condition of['stop','grant']){const ctx=setup(),p=probe();if(condition==='stop')ctx.unit.holdingPosition=true;else ctx.hasGrant=true;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,0);}});
test('eligibility loss permanently cancels the active attempt',()=>{const ctx=setup(),p=probe();const move=p.select(ctx);ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;ctx.tick++;ctx.unit.movePlanningPending=true;assert.equal(p.select(ctx),ctx.normal);ctx.unit.movePlanningPending=false;ctx.tick++;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,1);assert.equal(p.report.events.at(-1).reason,'eligibility-loss');});
test('query overflow cancels rather than pausing a retreat until the query clears',()=>{const ctx=setup(),p=probe();const move=p.select(ctx);ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;ctx.tick++;ctx.query.overflow=true;assert.equal(p.select(ctx),ctx.normal);ctx.query.overflow=false;ctx.tick++;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,1);assert.equal(p.report.events.at(-1).reason,'query-overflow');});
test('an unobserved own-turn gap invalidates the attempt even with unchanged route identity',()=>{const ctx=setup(),p=probe();const move=p.select(ctx);ctx.unit.x+=move.x*move.stepDistance;ctx.unit.z+=move.z*move.stepDistance;ctx.tick+=2;assert.equal(p.select(ctx),ctx.normal);ctx.tick++;assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.at(-1).reason,'observation-gap');assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,1);});
test('a parked actor at the projected target retains the original wait',()=>{const ctx=setup(),p=probe();ctx.query={visits:1,overflow:false,neighbors:[{...ctx.unit,id:1,kind:'worker',x:.5,z:.5,path:[],pathIndex:0}]};assert.equal(p.select(ctx),ctx.normal);assert.equal(p.report.events.at(-1).reason,'parked-target-wait');assert.equal(p.report.events.filter(e=>e.type==='retreat-step').length,0);});
