import test from 'node:test';
import assert from 'node:assert/strict';
import { guardFor, projectOrdinaryStep } from './crowd-executor-projection.mjs';
import { canTraverseCrowdBodySegment } from '../src/unit-crowd-steering.mjs';
const width=12,height=12;
const cell=(x,z)=>Math.floor(z+height/2)*width+Math.floor(x+width/2);
const point=c=>({x:c%width-width/2+.5,z:Math.floor(c/width)-height/2+.5});
const unit=(id,x=-1.5,z=.5)=>({id,team:0,generation:7,orderRevision:3,kind:'infantry',hp:100,x,z,path:[cell(.5,.5)],pathIndex:0,moveGoalCell:cell(.5,.5),queuedWaypoints:[],gatherNodeId:null,buildingTargetId:null});
function frame(u,neighbors=[]){return {unit:u,tick:9,navigationRevision:2,epoch:4,expected:guardFor(u,9,2,4),budget:{actor:u,tick:9,remainingStep:2.6/30,kind:'own-call'},query:{visits:neighbors.length,overflow:false,neighbors},map:{width,height,cell,point,levels:new Int8Array(width*height),isWalkable:()=>true}};}
test('own-call budget is explicit; future bounds cannot spend it',()=>{const u=unit(1),f=frame(u);assert.equal(projectOrdinaryStep(f).spendable,true);assert.equal(projectOrdinaryStep({...f,budget:{...f.budget,kind:'future-turn-bound'}}).spendable,false);for(const remainingStep of[0,-1,Infinity,.25])assert.equal(projectOrdinaryStep({...f,budget:{...f.budget,remainingStep}}).status,'unavailable-budget');assert.equal(projectOrdinaryStep({...f,budget:{...f.budget,actor:unit(2)}}).status,'unavailable-budget');});
test('identity, order, route, pose and phase guards refuse before reading query',()=>{const u=unit(1),f=frame(u);for(const [k,v]of Object.entries({actor:unit(2),generation:8,orderRevision:4,path:[...u.path],pathIndex:1,tick:8,navigationRevision:3,epoch:5,x:u.x+.001,z:u.z+.001})){const g={...f,expected:{...f.expected,[k]:v}};Object.defineProperty(g,'query',{get(){throw Error('stale query read');}});assert.equal(projectOrdinaryStep(g).status,'changed-route-or-pose');}});
test('query absence, incomplete metadata and overflow never claim clear room',()=>{const u=unit(1),f=frame(u);for(const query of[null,{neighbors:[],visits:0},{neighbors:[],visits:129,overflow:false},{neighbors:[],visits:-1,overflow:false},{neighbors:Array.from({length:65},(_,i)=>unit(i+2)),visits:65,overflow:false}])assert.equal(projectOrdinaryStep({...f,query}).status,'query-overflow');});
test('returns every physical body blocker in deterministic identity order',()=>{const u=unit(1),a=unit(3,-1.04,.58),b=unit(2,-1.04,.42),f=frame(u,[a,b]);const p=projectOrdinaryStep(f);assert.equal(p.strictClear,false);assert.deepEqual(p.bodyBlockers.map(b=>b.id),[2,3]);assert.ok(p.bodyBlockers.every(b=>b.margin<0));assert.equal(p.stats.bodyVisits,2);});
test('escape-admitted inherited body contact cannot count as strict clearance',()=>{const u=unit(1,0,.5),o=unit(2,-.3,.5),f=frame(u,[o]);u.path=[cell(2.5,.5)];u.moveGoalCell=u.path[0];f.expected=guardFor(u,9,2,4);const p=projectOrdinaryStep(f);assert.equal(canTraverseCrowdBodySegment(u,p.to,.22,[o],{allowEscape:true}),true);assert.equal(p.strictClear,false);assert.deepEqual(p.bodyBlockers.map(o=>o.id),[2]);});
test('strict static contact remains listed even when the short escape is admissible',()=>{const u=unit(1,-.15,-.15),f=frame(u);u.path=[cell(1.5,-.5)];u.moveGoalCell=u.path[0];f.expected=guardFor(u,9,2,4);const blocked=cell(.5,.5);f.map.isWalkable=c=>c!==blocked;const p=projectOrdinaryStep(f);assert.equal(p.status,'projected');assert.equal(p.strictClear,false);assert.ok(p.staticBlockers.some(b=>b.cell===blocked&&b.margin<0));});
test('Stop, pending planning and parked actors are ineligible',()=>{for(const extra of[{holdingPosition:true},{movePlanningPending:true},{pathIndex:1},{attackMove:true},{kind:'worker'}])assert.equal(projectOrdinaryStep(frame({...unit(1),...extra})).status,'ineligible');});
test('complete bounded query and passage projection do not mutate actors or consume orders',()=>{const u=unit(1);u.path=[cell(.5,.5),cell(1.5,.5)];const ns=Array.from({length:64},(_,i)=>unit(i+2,3+(i%8),3+Math.floor(i/8)));const f=frame(u,ns);f.query.visits=128;const before=structuredClone([u,...ns]);const p=projectOrdinaryStep(f);assert.equal(p.status,'projected');assert.ok(p.stats.passageProposals<=22);assert.ok(p.stats.passageBodyVisits<=22*64);assert.ok(p.stats.staticCells<=25);assert.equal(p.stats.bodyVisits,64);assert.deepEqual([u,...ns],before);});
